version: '3'
services:
  db.service:
    container_name: db
    image: postgres:9.5-alpine
    volumes:
      - ./data/database:/var/lib/postgresql/data
    env_file:
      - ./config/database.env
    ports:
      - "5432:5432"
  app.service:
    tty: true
    stdin_open: true
    container_name: app
    build: .
    env_file:
      - ./config/api.env
    ports:
      - "80:3000"
    volumes:
      - .:/app
    depends_on:
      - db.service